GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzAyNjUyNDY1LCJleHAiOjE3MDI2NTI0ODB9.J00-GxZziagPizBF4OlB29ZPtXrKasEmapTyP6UYR1A
###

POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "John Doe2",
    "email": "john2@gmail.com",
    "password": "password123",
    "confirmPassword": "password123"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "john2@gmail.com",
    "password": "password123"
}

###

GET http://localhost:8000/token

###

DELETE http://localhost:8000/logout

###

GET http://localhost:8000/cities

###

GET http://localhost:8000/categories

###

GET http://localhost:8000/cities/Surabaya


###

GET http://localhost:8000/categories/Budaya


###

GET http://localhost:8000/place

###

GET http://localhost:8000/place/Monumen Nasional

###

GET http://localhost:8000/food

###



###

GET http://localhost:8000/food/Asinan Betawi
